package adapters

import (
	"context"
	"crypto/rand"
	"fmt"
	"time"

	"github.com/oklog/ulid/v2"
)

// EventType enumerates the platform-agnostic events the adapter layer surfaces
// to the rest of engelOS. Adapters translate from their native wire format
// into one of these values.
type EventType string

const (
	EventMessageCreated   EventType = "message.created"
	EventMessageDeleted   EventType = "message.deleted"
	EventUserSubscribed   EventType = "user.subscribed"
	EventUserResubscribed EventType = "user.resubscribed"
	EventUserBanned       EventType = "user.banned"
	EventUserTimedOut     EventType = "user.timed_out"
	EventChannelRaided    EventType = "channel.raided"
	EventConnected        EventType = "platform.connected"
	EventDisconnected     EventType = "platform.disconnected"
	EventReconnecting     EventType = "platform.reconnecting"
)

// Event is the normalized, platform-neutral representation of something that
// happened on a connected platform. Exactly one of the specialized payload
// pointers should be non-nil; which one is determined by Type.
//
// ID is a ULID generated by the adapter (NOT the platform's native message
// id, which lives in the specialized payload). The ULID gives the rest of the
// system a globally-unique, lexicographically time-sortable identifier even
// across platforms that don't natively provide one.
type Event struct {
	ID         string    `json:"id"`
	Type       EventType `json:"type"`
	Platform   string    `json:"platform"`
	Channel    string    `json:"channel"`
	OccurredAt time.Time `json:"occurred_at"`

	Message      *MessageEvent      `json:"message,omitempty"`
	Subscription *SubscriptionEvent `json:"subscription,omitempty"`
	Raid         *RaidEvent         `json:"raid,omitempty"`
	UserAction   *UserActionEvent   `json:"user_action,omitempty"`
	Connection   *ConnectionEvent   `json:"connection,omitempty"`
}

// MessageEvent carries the payload for [EventMessageCreated] and (with
// Content typically empty) for [EventMessageDeleted].
type MessageEvent struct {
	ID           string   `json:"id"`
	UserID       string   `json:"user_id"`
	Username     string   `json:"username"`
	Content      string   `json:"content"`
	IsModerator  bool     `json:"is_moderator"`
	IsSubscriber bool     `json:"is_subscriber"`
	IsVIP        bool     `json:"is_vip"`
	Badges       []string `json:"badges,omitempty"`
	EmotesUsed   []string `json:"emotes_used,omitempty"`
	ReplyTo      string   `json:"reply_to,omitempty"`
}

// SubscriptionEvent carries the payload for [EventUserSubscribed] and
// [EventUserResubscribed]. Tier values are platform-specific strings (Twitch
// uses "1000"/"2000"/"3000"/"prime"); the adapter layer makes no attempt to
// normalize them.
type SubscriptionEvent struct {
	UserID      string `json:"user_id"`
	Username    string `json:"username"`
	Tier        string `json:"tier"`
	MonthsTotal int    `json:"months_total"`
	IsGift      bool   `json:"is_gift"`
	GiftedBy    string `json:"gifted_by,omitempty"`
	Message     string `json:"message,omitempty"`
}

// RaidEvent carries the payload for [EventChannelRaided].
type RaidEvent struct {
	FromUsername string `json:"from_username"`
	ViewerCount  int    `json:"viewer_count"`
}

// UserActionEvent carries the payload for moderation-style events
// ([EventUserBanned], [EventUserTimedOut], and arbitrary role changes the
// adapter wishes to surface — mod_added, vip_added, untimeout, ...).
type UserActionEvent struct {
	Action     string        `json:"action"`
	TargetUser string        `json:"target_user"`
	Moderator  string        `json:"moderator,omitempty"`
	Reason     string        `json:"reason,omitempty"`
	Duration   time.Duration `json:"duration,omitempty"`
}

// ConnectionEvent carries the payload for [EventConnected],
// [EventDisconnected] and [EventReconnecting]. Reason is a short
// human-readable description; Error is the underlying error message if there
// is one.
type ConnectionEvent struct {
	Reason string `json:"reason,omitempty"`
	Error  string `json:"error,omitempty"`
}

// ActionType enumerates the platform-agnostic actions the bot can ask an
// adapter to perform.
type ActionType string

const (
	ActionSendMessage   ActionType = "send_message"
	ActionDeleteMessage ActionType = "delete_message"
	ActionBan           ActionType = "ban"
	ActionTimeout       ActionType = "timeout"
	ActionUntimeout     ActionType = "untimeout"
)

// Action is the normalized request to perform something on a platform.
// Exactly one of the specialized payload pointers should be non-nil; which
// one is determined by Type.
type Action struct {
	Type    ActionType `json:"type"`
	Channel string     `json:"channel"`

	SendMessage   *SendMessageAction   `json:"send_message,omitempty"`
	DeleteMessage *DeleteMessageAction `json:"delete_message,omitempty"`
	Ban           *BanAction           `json:"ban,omitempty"`
	Timeout       *TimeoutAction       `json:"timeout,omitempty"`
	Untimeout     *UntimeoutAction     `json:"untimeout,omitempty"`
}

// SendMessageAction is the payload for [ActionSendMessage]. ReplyTo, if set,
// is the platform-native message id this message replies to.
type SendMessageAction struct {
	Text    string `json:"text"`
	ReplyTo string `json:"reply_to,omitempty"`
}

// DeleteMessageAction is the payload for [ActionDeleteMessage].
type DeleteMessageAction struct {
	MessageID string `json:"message_id"`
}

// BanAction is the payload for [ActionBan].
type BanAction struct {
	UserID string `json:"user_id"`
	Reason string `json:"reason,omitempty"`
}

// TimeoutAction is the payload for [ActionTimeout].
type TimeoutAction struct {
	UserID   string        `json:"user_id"`
	Reason   string        `json:"reason,omitempty"`
	Duration time.Duration `json:"duration"`
}

// UntimeoutAction is the payload for [ActionUntimeout].
type UntimeoutAction struct {
	UserID string `json:"user_id"`
}

// Platform is the contract every streaming-platform adapter must implement.
//
// Implementations are expected to be safe for concurrent use: Do may be
// invoked from many goroutines while a single consumer is reading from
// Events.
type Platform interface {
	// Name returns the short identifier of this platform, e.g. "twitch",
	// "discord", "youtube", "kick". The same string is copied into
	// Event.Platform for every event this adapter emits.
	Name() string

	// Connect establishes the underlying connection (IRC, WebSocket, gRPC,
	// ...) and starts producing events on the channel returned by Events.
	// Connect MUST be safe to call exactly once per Platform value; calling
	// it twice is implementation-defined.
	Connect(ctx context.Context) error

	// Disconnect tears down the underlying connection and closes the channel
	// returned by Events. It is safe to call Disconnect even if Connect was
	// never called or already failed.
	Disconnect(ctx context.Context) error

	// Events returns a receive-only channel that delivers normalized
	// [Event] values in the order the platform reported them. The channel
	// is closed when the platform is fully disconnected and will produce no
	// more events on the current connection.
	Events() <-chan Event

	// Do executes a platform action. It blocks until the action has been
	// dispatched (which, depending on the platform, may mean acknowledged
	// by the server). Do MUST honor ctx cancellation.
	Do(ctx context.Context, action Action) error

	// Health returns nil if the underlying connection is currently healthy
	// and able to send/receive, or an error describing the unhealthy state
	// otherwise. Health MUST NOT block on network I/O — it reports cached
	// state maintained by the adapter.
	Health() error
}

// NewEventID generates a fresh ULID suitable for [Event.ID]. Adapter
// implementations should call this exactly once per event they produce so
// that the rest of engelOS can rely on globally-unique, time-sortable ids.
func NewEventID() string {
	now := time.Now().UTC()
	id, err := ulid.New(ulid.Timestamp(now), rand.Reader)
	if err != nil {
		// crypto/rand.Reader failing is, in practice, a fatal kernel-level
		// problem. Surface it as a panic rather than silently returning an
		// empty id that would corrupt downstream invariants.
		panic(fmt.Errorf("adapters: generate ulid: %w", err))
	}
	return id.String()
}
